stages:
  - build
#  - badges

buildWindows512:
  stage: build
  script:
    - .\tests\build\build-512.bat 1>buildLog.txt
  tags:
    - Win7Qt512
  artifacts:
    paths:
      - lib/core/GTlabNumerics.dll
      - lib/core/GTlabNumerics.lib
      - lib/core/GTlabNumerics.pdb
      - build/GTlabUnitTest.exe
      - build/GTlabUnitTest.pdb
      - buildLog.txt
    when: always  	  
      
nightlyBuildWindowsQt512:
  stage: build
  script:
    - .\tests\build\build-nightly-512.bat
    - .\tests\build\copyHeaders-512.bat
  tags:
    - Win7Qt512
  only:
    - master    
       

#badges:
#  stage: badges
#  script:
#    - $CommitNumber = git rev-list --count HEAD
#    - .\tests\badges\badges.bat --run commits $CommitNumber
#    - $statistics = git diff --shortstat 4b825dc642cb6eb9a060e54bf8d69288fbee4904
#    - $filesRaw,$linesRaw = $statistics.split(',')
#    - $fileNumber = $filesRaw.split(' ')[1]
#    - $linenumber = $linesRaw.split(' ')[1]
#    - .\tests\badges\badges.bat --run files $fileNumber
#    - .\tests\badges\badges.bat --bw .\buildLog.txt .
#
#  tags:
#    - Windows7
#  artifacts:
#    paths:
#      - "New_commits.svg"
#      - "New_files.svg"
#      - "New_BuildWarn-W.svg"
#  
