stages:
  - build
  - test
  - codingstyle
  - badges

buildWindows512:
  stage: build
  script:
    - .\tests\build\build-512.bat 1>buildLog.txt
  tags:
    - Win7Qt512
  artifacts:
    paths:
      - lib/core/GTlabDatamodel-d.dll
      - lib/core/GTlabDatamodel-d.lib
      - build/GTlabDatamodel-d.pdb
      - lib/core/GTlabCalculators-d.dll
      - lib/core/GTlabCalculators-d.lib
      - build/GTlabCalculators-d.pdb
      - lib/core/GTlabCore-d.dll
      - lib/core/GTlabCore-d.lib
      - build/GTlabCore-d.pdb
      - lib/core/GTlabNetwork-d.dll
      - lib/core/GTlabNetwork-d.lib
      - build/GTlabNetwork-d.pdb
      - build/GTlabGui-d.pdb
      - build/GTlabGui-d.dll
      - build/GTlabGui-d.lib
      - lib/core/GTlabMdi-d.dll
      - lib/core/GTlabMdi-d.lib
      - build/GTlabMdi-d.pdb		  
      - build/GTlab.exe
      - build/GTlabConsole.exe
      - build/GTlabUnitTest.exe
      - buildLog.txt
    when: always  	  
  variables:
    DEVTOOLS: "C:\\devel\\GTlab-DevTools\\stable\\1_6"   
    BUILD_UNIT: "true"
    
nightlyBuildWindowsQt512:
  stage: build
  script:
    - .\tests\build\build-nightly-512.bat
    - .\tests\build\copyHeaders-512.bat
  artifacts:
    paths:
      - lib/core/GTlabDatamodel.dll
      - lib/core/GTlabDatamodel.lib
      - lib/core/GTlabCalculators.dll
      - lib/core/GTlabCalculators.lib
      - lib/core/GTlabCore.dll
      - lib/core/GTlabCore.lib
      - lib/core/GTlabNetwork.dll
      - lib/core/GTlabNetwork.lib
      - build/GTlabGui.dll
      - build/GTlabGui.lib
      - lib/core/GTlabMdi.dll
      - lib/core/GTlabMdi.lib	  
      - build/GTlab.exe
      - build/GTlabConsole.exe	  
      - include/core/*.h   		  
  tags:
    - Win7Qt512
  only:
    - master    
  variables:
    DEVTOOLS: "C:\\devel\\GTlab-DevTools\\stable\\1_6"           
    NIGHTLYBUILD: "G:\\AT-TW\\GTlab\\Nightly_Builds_512"
    BUILD_UNIT: "false"
    
buildLinux:
  stage: build
  before_script:
    # add permissions
    - chmod +x ./tests/build/build-512.sh
  script:
    - ./tests/build/build-512.sh 1 > linuxBuild.txt
  tags:
    - LinuxTest
  artifacts:
    paths:
    - linuxBuild.txt
    - lib/core/*.so*
    - build/GTlab
    - build/GTlabConsole
    - build/libGTlabGui.so
  variables:
    DEVTOOLS: "/home/gitlab-runner/gtlab-devtools"     
    BUILD_UNIT: "false"    
guiTests:
  needs: ["buildLinux"]
  stage: test
  tags:
    - LinuxTest
  dependencies:
    - buildLinux
  before_script:
    # add permissions
    - chmod +x ./tests/guitests/run_guitests.sh
  script:
    # xvfb to run a virtual display
    - xvfb-run ./tests/guitests/run_guitests.sh
  artifacts:
    paths:
      - ./gui_tests_web
      - ./gui_tests_junits
      - ./gui_tests_stdout*.txt     
      - ./gui_tests_server_stdout.txt  
      - ./gui_tests_server_stdout.txt
      - ./guitests_badge.svg  
    reports:
      junit: ./gui_tests_junits/junit*.xml
    name: "guitesting results"
    expire_in: 1 week
    when: always
  variables:
    DEVTOOLS_DIR: "/home/gitlab-runner/gtlab-devtools"    

testWin512:
  needs: ["buildWindows512"]
  stage: test
  script:
    - .\tests\unittests\runUnittestsQt512.bat
  dependencies:
    - buildWindows512
  tags:
    - Win7Qt512
  artifacts:
    paths:
      - "unittests.xml"
      - "GTlabUnitTestCoverage.xml"   
      - CoverageReport*      
    reports:
      junit: unittests.xml
    expire_in: 1 week
  variables:
    DEVTOOLS: "C:\\devel\\GTlab-DevTools\\stable\\1_6" 

codingstyle:
  stage: codingstyle
  script:
    - .\tests\codingstyle\runCodingstyle.bat 1>codingStyleLog.txt
  tags:
    - Win7Qt512
  artifacts:
    paths:
      - "nsiqcppstyle_report.xml"
      - codingStyleLog.txt
    expire_in: 1 week
badges:
  stage: badges
  script:
    - $CommitNumber = git rev-list --count HEAD
    - .\tests\badges\badges.bat --run commits $CommitNumber
    - $statistics = git diff --shortstat 4b825dc642cb6eb9a060e54bf8d69288fbee4904
    - $filesRaw,$linesRaw = $statistics.split(',')
    - $fileNumber = $filesRaw.split(' ')[1]
    - .\tests\badges\badges.bat --run files $fileNumber
    - .\tests\badges\badges.bat --bw .\buildLog.txt .
    - .\tests\badges\badges.bat --cs .\codingStyleLog.txt .	
    - .\tests\badges\badges.bat --cl .\GTlabUnitTestCoverage.xml .
    - .\tests\badges\badges.bat --cc .\GTlabUnitTestCoverage.xml .
    - .\tests\badges\badges.bat --bw .\linuxBuild.txt .  
  tags:
    - Win7Qt512
  artifacts:
    paths:
      - "New_commits.svg"
      - "New_lines.svg"
      - "New_files.svg"
      - "New_BuildWarn-W.svg"
      - "New_BuildWarn-L.svg"
      - "New_CodingStyle.svg"
      - "New_Coverage.svg"
    expire_in: 26 week  
  
